openapi: 3.0.3
info:
  title: UnisonUI
  description: >
    UnisonUI is a webapp which gather all your OpenApi, AsyncAPI and gRPC specifications in one place
  license:
    name: MIT
    url: https://raw.githubusercontent.com/UnisonUI/unisonui/master/LICENSE
  version: 2.0.0
paths:
  /services:
    get:
      summary: List all available services
      responses:
        200:
          description: Available services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
              example:
                - event: serviceUp
                  id: serviceId
                  name: serviceName
                  metadata:
                    file: /specification.yaml
                    provider: someProvider
        500:
          description: Something bad happened
          content:
            text/plain:
              schema:
                type: string
  /services/{serviceId}:
    get:
      summary: Get the specification of a service
      parameters:
        - name: serviceId
          in: path
          description: Service's id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Return the speicifation of a service
          content:
            text/plain:
              schema:
                type: string
        404:
          description: The service is not available
          content:
            text/plain:
              schema:
                type: string
              example: serviceId is not registered
components:
  schemas:
    Event:
      type: object
      required:
        - event
        - id
      properties:
        event:
          type: string
          enum: ["serviceUp", "serviceDown"]
          description: Event's type
        id:
          type: string
          description: Service's id
        name:
          type: string
          description: Service's name
        metadata:
          type: object
          description: Service's metadata
