env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  "react/prop-types": "off"
  "react/display-name": "off"
settings:
  react:
    version: detect
