name: Docusaurus
on:
  push:
    branches: ["master"]
    paths: ["docsite/**"]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Build Docusaurus website
        run: |
          cd docsite
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: master
          repo: UnisonUI/unisonui.github.io
          build_dir: docsite/build
          fqdn: unisonui.tech
        env:
          GH_PAT: ${{ secrets.TOKEN }}
